# For more information, please refer to https://aka.ms/vscode-docker-python
# FROM python:3-slim
FROM huggingface/transformers-quantization-latest-gpu

WORKDIR /workdir
COPY . .

# RUN python -m pip install --upgrade pip \
#     && python -m pip install -r ./.devcontainer/requirements.txt

# RUN python -m pip install elasticsearch \
#     && python -m pip install eland


# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["python", "aste_etl.py"]
